#
# Makefile for all kinds of Fingerprint
#
#+Bug584789 liaomingzhe.wt, ADD, 20200928, fingerprint bringup
obj-$(CONFIG_CDFINGER_RO) += cdfinger_fp_tee_ro/
obj-$(CONFIG_CHIPONE_FINGERPRINT) += fpsensor/
#-Bug584789 liaomingzhe.wt, ADD, 20200928, fingerprint bringup
#+Bug591035, xiaoguang.wt, add, 20200928, add fingerprint driver bringup
obj-$(CONFIG_CDFINGER_FP) += cdfinger_fp_tee/
obj-$(CONFIG_SILEAD_FP) += silead/
#-Bug591035, xiaoguang.wt, add, 20200928, add fingerprint driver bringup

